### ISSUE TITLE
]quit incorrectly restarts the bot (and cannot be fixed)

### ISSUE THREAD

**Issue by ukbigdave** [soulus98/PoGo-profile-level-scanner#35]
When using quit - the bot seems to just restart 
![image](https://user-images.githubusercontent.com/65876553/126923466-190728d5-7d6a-4920-beb5-4e9bf05c2c5a.png)

The log file in the server, dont want to publish to a public forum.

**Comment by ukbigdave** [comment]
To add, if i use ]quit in the logs channel, it shows restart in the main channel. 

Im not sure this is an issue, and being able to restart it is no bad thing i guess

**Comment by soulus98** [comment]
In v1.3, I'll rename it to ”restart".
If I find out what causes it I'll make a new quit command.
Quit works fine as is in nodemon, though, so it must be something the server hosting is doing.

**Comment by soulus98** [comment]
As far as I can find, PM2 can't exit gracefully through process.exit() without a restart
So unless we use a different daemon/docker thingy, `]quit` just isn't a thing

I've edited the title
Let me know if you want me to remove the command or if you research an alternative
