### ISSUE TITLE
Help to be context sensitive for manage guild

### ISSUE THREAD

**Issue by ukbigdave** [soulus98/PoGo-profile-level-scanner#37]
Can the help that differentiates 'admin' from general member be moved to 'manage server'
![image](https://user-images.githubusercontent.com/65876553/126996286-a6e2eb88-46fb-434f-a27d-e9dc3d573515.png)

**Comment by ukbigdave** [comment]
help.js, line 16
		if (!message.channel.permissionsFor(message.author).has("MANAGE-GUILD")){

**Comment by soulus98** [comment]
Fixed in v1.1
