### ISSUE TITLE
Dont create screenshot folders when saveLocalCopy = false

### ISSUE THREAD

**Issue by ukbigdave** [soulus98/PoGo-profile-level-scanner#38]
Dont see any need for it to create folders every day that will be empty. 

Low priority

![image](https://user-images.githubusercontent.com/65876553/126997548-5e2d738c-a584-4173-9fd7-4dcc66e692db.png)

**Comment by soulus98** [comment]
Should be an easy fix

**Comment by soulus98** [comment]
Fixed in v1.6
