### ISSUE TITLE
Dont log all member joins

### ISSUE THREAD

**Issue by ukbigdave** [soulus98/PoGo-profile-level-scanner#39]
We are logging all member joins -  i dont think this is needed - will make the log very big :)

![image](https://user-images.githubusercontent.com/65876553/127081012-72ab0261-6929-48b5-abcc-16bda20c9533.png)
![image](https://user-images.githubusercontent.com/65876553/127081060-c34992df-7159-403f-a13a-ce48ad225aab.png)

**Comment by soulus98** [comment]
Yeah that does seem annoying
Will fix in v1.3

**Comment by soulus98** [comment]
@ukbigdave now that this isn't necessary, and we aren't using the welcome message, feel free to turn off "server members intent" in discord developer settings

**Comment by soulus98** [comment]
Removed in v1.3
"Server Members Intent" should no longer be necessary. I've tested it, so not sure what is wrong if there's an issue.
