### ISSUE TITLE
Delay profile post longer

### ISSUE THREAD

**Issue by soulus98** [soulus98/PoGo-profile-level-scanner#43]
Perhaps 2 seconds would be good
That way, it isn't popping up at the same time as the DM, and is a good 2nd chance to get their attention
Will fix in v1.3

**Comment by soulus98** [comment]
I've made a delay. Haven't tested if it works

**Comment by ukbigdave** [comment]
In my testing, it looks like the delay gets added to the role assignment too - i went up to 15000 and the channel didn't show for 15 seconds, and no 'ping' was received (although the message was sent into the channel)

**Comment by soulus98** [comment]
@ukbigdave Ah okay. If they're synced then that's probably why my initial delay of 250ms didn't work. Will look at tomorrow

**Comment by soulus98** [comment]
Fixed in v1.3
