### ISSUE TITLE
]approve command

### ISSUE THREAD

**Issue by soulus98** [soulus98/PoGo-profile-level-scanner#51]
]approve @user level function - ]approve ukbigdave/656655566 46 - that staff could use in post screenshots/screenshot logs for the manual approval.
This would set the roles, fire DM/tag in profile-setup.

Would require me to clean up functions/modules a lot, but could be done.

**Comment by soulus98** [comment]
]a as an alias for ease

**Comment by ukbigdave** [comment]
Suggest letting this function work for under 30, ie, the 29.5 scenario.

**Comment by ukbigdave** [comment]
maybe add a ]r for reject too that sends the <30 message

**Comment by soulus98** [comment]
Done and dusted (hopefully), v1.7
