### ISSUE TITLE
CRITICAL ISSUE - Multiple images deleted on one ]c

### ISSUE THREAD

**Issue by ukbigdave** [soulus98/PoGo-profile-level-scanner#60]
Upload an unreadable image with account 1
Upload an unreadable image with account 2

(both errored in the screenshot channel)

]c the first image, both are deleted.

**Comment by soulus98** [comment]
@ukbigdave this is fine, right? Since both images were sent by the same (now approved) user.
It won't delete messages from other users.

**Comment by ukbigdave** [comment]
close
