### ISSUE TITLE
Idea: Make 29 not blacklist

### ISSUE THREAD

**Issue by soulus98** [soulus98/PoGo-profile-level-scanner#69]
To allow for a quick level-up and repost

**Comment by soulus98** [comment]
Also, people that are 29, then trick the bot, probably aren't a big deal to worry about

Note: will have to factor in the level40+ server. Perhaps I could make "gateLevel" a setting

**Comment by ukbigdave** [comment]
I wondered if it could tag moderator in the logs channel for manual review if "target level -1" - a 'target level' could then be a parameter for usage in other scenarios - maybe too much rework, but you have level 1 role, level 2 role, level 3 roles with parameters and use in the code.

**Comment by soulus98** [comment]
Added in upcoming v1.8
